package:
  name: exdir-browser
  version: {{ environ.get("GIT_DESCRIBE", "unknown_version")|replace("v", "")|replace("-", "_") }}
  
source:
  path: .
 
requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - quantities
    - pyyaml
    - pyqt

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - quantities
    - pyyaml
    - exdir

test:
  imports:
    - exdirbrowser

about:
  home: https://github.com/CINPLA/exdir-browser/
  license: GPLv3
  license_file: LICENSE
