package:
  name: exdir-browser
  version: {{ environ.get("GIT_DESCRIBE", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

build:
  number: 1

source:
  git_url: ..

requirements:
  build:
    - boost
    - boost-cpp
    - gcc
    - libgcc
    - qt
    - yaml

about:
  home: https://github.com/CINPLA/exdir-browser/
  license: GPLv3
  license_file: LICENSE
